version: '3'

services:
  web:
    build: .
    command: uwsgi --ini wsgi.ini
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres:11.2
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: popo
      POSTGRES_DB: popo
    ports:
      - "5432:5432"
